version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deliveryapp
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "deliveryapp@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  pgdata: