# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  orderserviceapi:
    image: orderserviceapi
    build:
      context: .
      dockerfile: order-service-api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5284:5284
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
